### ISSUE TITLE
Missing variable

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/bsg_manycore#105]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/5f5c3b975396e6e87e3c00688d9facb536ea07ef/machines/Makefile#L16

BASEJUMP_STL does not seem to be set

Please remove environment variables from .bashrc or .profile to avoid these kind of reproducibility errors.

**Comment by drichmond** [comment]
I think this is fixed
