### ISSUE TITLE
reduce requirements of riscv-tools

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/bsg_manycore#106]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/5f5c3b975396e6e87e3c00688d9facb536ea07ef/software/riscv-tools/Makefile#L1

After installing the riscv-tools, the makefile should do a cleaning pass that removes the intermediate build files that are no longer needed. This will save huge amounts of space on disk across our cluster.

**Comment by vb000** [comment]
Implemented these updated in `toolchain_updates` branch. Have a look at the changes [here](https://github.com/bespoke-silicon-group/bsg_manycore/compare/toolchain_updates).
