### ISSUE TITLE
Add bsg_remote_int_ptr and bsg_remote_float_ptr

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_manycore#109]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/ce763c2e08c4cbe2ae8294b827dad297bdf8a2d7/software/bsg_manycore_lib/bsg_manycore_arch.h#L68

**Comment by drichmond** [comment]
Fixed?

**Comment by bornaehsani** [comment]
Yes, addressed in PR #112. Thanks for pointing it out!
