### ISSUE TITLE
striped_hello time out

### ISSUE THREAD

**Issue by tommydcjung** [bespoke-silicon-group/bsg_manycore#114]
striped_hello times out for 4x4, but it works fine for 9x15.

**Comment by tommydcjung** [comment]
however, the test passes when the tile group is placed elsewhere (e.g. x=1,y=1)

**Comment by tommydcjung** [comment]
```
F P P x
F F P x
F F P x
x x x x

F = fail
P = Pass
x = N/A
```

**Comment by tommydcjung** [comment]
```
P P P P P P P P x
P ? ? ? ? ? ? ? x
P ? ? ? ? ? ? ? x
P ? ? ? ? ? ? ? x
P ? ? ? ? ? ? ? x
P ? ? ? ? ? ? ? x
P ? ? ? ? ? ? ? x
F ? ? ? ? ? ? ? x
F ? ? ? ? ? ? ? x
F ? ? ? ? ? ? ? x
F ? ? ? ? ? ? ? x
F ? ? ? ? ? ? ? x
F F F P P ? ? ? x
F F F F P P P P x
x x x x x x x x x

?=haven't tried

**Comment by tommydcjung** [comment]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/debug_20190731/software/spmd/striped_minimal/main.c

**Comment by tommydcjung** [comment]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/debug_20190731/software/spmd/striped_minimal/main.c#L15
```
while (A[i][id] != (id * 2) + i * 5);
```
this line is supposed to check if the other tile has written to the striped array.
this corresponds to the instruction with PC=dcc.
```
     dc8: 00159f13            slli  x30,x11,0x1
     dcc: 00062603            lw  x12,0(x12)
     dd0: 19e61a63            bne x12,x30,f64 <main+0x4c8>
```

then it jumps to pc=f64, which is just infinite loop. This is incorrect, because the program is supposed to keep loading the value until it gets the value stored by the other tile. So I suspected that something is wrong with the compilation.


```
     f5c: aca5a823            sw  x10,-1328(x11) # 4000ead0 <_bsg_elf_vcache_size+0x3ffeead0>
     f60: 0000006f            j f60 <main+0x4c4>
     f64: 0000006f            j f64 <main+0x4c8>
```

solution: change the gcc flag from -O2 to -O0.

**Comment by tommydcjung** [comment]
might want to figure out what -O flag we want to use for each type of spmd program.

**Comment by max-ruttenberg** [comment]
@tommydcjung you might need to mark A as volatile?

**Comment by max-ruttenberg** [comment]
In a single threaded context that value would never change. With -O2 flag the compiler looks at that line of code and says "Hm... why even bother doing the comparison more than once? Just check the first time and then spin for ever if it's not the exit condition of this loop."

**Comment by taylor-bsg** [comment]
Agree with Max.

M

**Comment by vb000** [comment]
Hi @tommydcjung, changing optimization flag is not the solution... had suggested it just as a way to debug. As Max suggested, A has to be volatile.

https://github.com/bespoke-silicon-group/bsg_manycore/blob/05e2d37da444bdfb1303fa1c568bec8a5eead5eb/software/spmd/striped_minimal/main.c#L7
To make the data volatile above line should be `volatile int STRIPE A[N][N];`. Note that `int STRIPE volatile A[N][N]` wouldn't work as that makes the pointer volatile.

**Comment by vb000** [comment]
Hi @neildryan, could you check whether this should be volatile?

https://github.com/bespoke-silicon-group/bsg_manycore/blob/1541a37abe67e068a1492686a3650adfb798d98b/software/spmd/striped_hello/main.c#L18

**Comment by taylor-bsg** [comment]
Tommy, to clarify, which version of the LLVM compiler is this being run
with?  Neil has the STRIPE keyword and his compiler is supposed to
autoinsert the appropriate volatileness.

M

**Comment by tommydcjung** [comment]
```
$ /mnt/bsg/diskbits/neilryan/llvm/llvm-install/bin/clang -v
clang version 7.0.1 (tags/RELEASE_701/final)
Target: riscv32-unknown--elf
Thread model: posix
InstalledDir: /mnt/bsg/diskbits/neilryan/llvm/llvm-install/bin
Found candidate GCC installation: /mnt/bsg/diskbits/neilryan/local/lib/gcc/riscv32-unknown-elf/8.2.0
Selected GCC installation: /mnt/bsg/diskbits/neilryan/local/lib/gcc/riscv32-unknown-elf/8.2.0
```

**Comment by tommydcjung** [comment]
`volatile int STRIPE A[N][N];` having volatile in front does not solve the problem. I will have to check if this is caused by another issue.

**Comment by neildryan** [comment]
I'll poke into it today -- there were some issues in the past with making sure the array was volatile

**Comment by neildryan** [comment]
@tommydcjung Do we have an idea of when the last time this test was working on the HW? Was it part of the regression?

**Comment by neildryan** [comment]
Or, rather, it works on 75219ce -- I feel like something in between changed. The volatility problem should be inferred by the compiler -- that worked fine back when I submitted that commit.

**Comment by taylor-bsg** [comment]
Seems like it is a software issue though? The code is not race free, and
there are no volatiles to indicate that a load needs to be reperformed.

M

**Comment by neildryan** [comment]
So, looks like the `volatile` keyword isn't being respected by the LLVM pass -- I'll fix that today. This stands by the original approach of putting the onus on the programmer to avoid data races with barriers and `volatile` pointers.

**Comment by taylor-bsg** [comment]
Well, I think it goes to the question of intent. How do you want to convey
to LLVM what you want? I think generally we want striping to only load and
store once per BSP (bulk synchronous parallel) section, but we need a way
to convey those sections to LLVM?

M

**Comment by neildryan** [comment]
I think that loading and storing in BSP sections gets handled quite nicely through tilegroup barriers -- the FFT test does this, I feel like this is the case that volatile was made for -- spin-waiting for another thread to modify a memory location

**Comment by tommydcjung** [comment]
might be a good idea to test this FFT code in every possible location where tile-group can be placed, but I think moving around tile-group can be done better in bsg_f1. @drichmond 
also tile-group with larger dimension that uses STRIPE (e.g. 4x4).

**Comment by taylor-bsg** [comment]
How does LLVM detect the beginning / end of a bsp section? What is it
looking at?

M

**Comment by tommydcjung** [comment]
I know the PR is already merged, but there are some fixes needed related to bsg_X and bsg_Y. made some comments on PR...

**Comment by tommydcjung** [comment]
it seems like extern_load/store_{type} is a lot more instructions than a single remote load/store. is that fair to say?

**Comment by neildryan** [comment]
That's fair to say -- it's more work to do the array_index -> EPA calculation than to just do a single load, although this could be offset by HW acceleration

**Comment by drichmond** [comment]
Is this fixed?

**Comment by tommydcjung** [comment]
I think we can close this
