### ISSUE TITLE
clarification on vanilla core synthesis

### ISSUE THREAD

**Issue by yswntht** [bespoke-silicon-group/bsg_manycore#120]
I see from the README `RISC-V 32IM compatible core runs at 1.4GHz@16nm`. Does that mean the Timing should be `MET/ No Violations` when vanilla core synthesized at 1.4GHz? because I see clock period to be 10000ns as period (or) 100KHz frequency from the synthesis tcl script.

Thanks.

**Comment by taylor-bsg** [comment]
Thanks for your message. Which script?

**Comment by yswntht** [comment]
In the command `create_clock -period 10000 $(CLK_PIN);` from [Makefile.dc](https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/syn/Makefile.dc)

**Comment by taylor-bsg** [comment]
Ah I see — we don’t use that directory any more (probably we should remove
it.)

This directory has the files for a recent tapeout:

https://bitbucket.org/taylor-bsg/bsg_designs/src/master/toplevels/bsg_ac_manycore_fpu_rc3/

Without any optimization, it hits 1 ns in the worst case PVT, so 1.4 GHz is
easily attainable under more typical conditions.

M

**Comment by yswntht** [comment]
Thank you for sharing the link.
