### ISSUE TITLE
rename enum for readability

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/bsg_manycore#121]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/56b7e4894e29fe8ded697541bd70d9173b1ddcc3/testbenches/common/v/bsg_mem_cfg_pkg.v#L13

rename to something more descriptive, maybe _vcache instead of _default.

**Comment by tommydcjung** [comment]
we will name this one e_mem_cfg_vcache_axi. and when we have a non-blocking cache ready, we will add e_mem_cfg_nbcache_dmc with bsg_dmc.
