### ISSUE TITLE
Building toolchains for bsg_manycore

### ISSUE THREAD

**Issue by duyhieubui** [bespoke-silicon-group/bsg_manycore#150]
It seems that the Makefile to build the toolchain in the master branch are not updated yet.
"make tools" shows the errors that the path "software/spmd/riscv-tools" does not exist.
The correct one should be "software/riscv-tools"

In addition, in "software/riscv-tools/Makefile", the following command does not work on Centos 6 and our git version (git version 1.7.1):

`git submodule update --init --recursive --remote riscv-newlib`

To make it work on Centos 6's default git, '--remote' should be replaced by '--reference'.

**Comment by taylor-bsg** [comment]
Thanks for your feedback! Would you be able to submit a pull request?

**Comment by duyhieubui** [comment]
Yes, I've just created the pull request. I found out that '--remote' has been introduced since git version 2.x. Therefore, in the pull request, I removed '--remote' from git-submodule command. It works on both Git 2.x and Git 1.7. However, I am not sure about the differences when adding '--remote' or '--reference' to git submodule.

**Comment by duyhieubui** [comment]
Yes, I will close this issue.
