### ISSUE TITLE
Expf issue

### ISSUE THREAD

**Issue by vb000** [bespoke-silicon-group/bsg_manycore#157]
Borna and I had a discussion about the expf issue and created the following demo of the issue:

https://github.com/bespoke-silicon-group/bsg_manycore/tree/fp_issue/software/spmd/expf

Spike and manycore running the same binary produces different results. Spike result seems to br correct as it matches with x86 result.

**Comment by taylor-bsg** [comment]
To repeat Tommy’s question, Is spike just using x86 floating point ops or
is it actually doing bit-level emulation?

**Comment by vb000** [comment]
Hi @taylor-bsg, thought Tommy's question was whether expf is compiled as a riscv instruction or software emulated (newlib call). So, I clarified that both binaries are the same (manycore binaries never have exp instruction). And, Tommy seemed to have narrowed down the issue to fma instructions which we don't support, just tracking the issue here.

But about the Spike implementation, Spike seems to use softfloat.

**Comment by taylor-bsg** [comment]
Okay I see — so this is suggesting a divergence with soft float.

M

**Comment by tommydcjung** [comment]
are you compiling newlib binaries with `-ffp-contract=off` flag? that should have prevented generating fma instructions in binary.

**Comment by vb000** [comment]
@tommydcjung we only customize a portable portion of newlib called `libgloss` that implements system calls. But the code causing this error is the actual math library, `libm`. I'm in fact trying what you suggested -- figuring out a clean way to add our compile-time options to library compilation flow. `riscv-gnu-toolchain`'s configure script does not have an option to pass target C flags. We might have to patch it to enable what we need.

**Comment by vb000** [comment]
Fixed with the toolchain update.
