### ISSUE TITLE
Test compilation toolchain with ilp32f ABI

### ISSUE THREAD

**Issue by vb000** [bespoke-silicon-group/bsg_manycore#162]
This can improve performance significantly as FP registers would be used for passing arguments.

**Comment by taylor-bsg** [comment]
Interesting!

**Comment by vb000** [comment]
This is not straightforward because of following issue:
https://github.com/riscv/riscv-gnu-toolchain/issues/530

So implemented with a patch to riscv-gcc.

**Comment by drichmond** [comment]
Addressed in #187?

**Comment by vb000** [comment]
Yes, addressed in https://github.com/bespoke-silicon-group/bsg_manycore/pull/187
