### ISSUE TITLE
Blood graph program stumbles on SLRI

### ISSUE THREAD

**Issue by mrutt92** [bespoke-silicon-group/bsg_manycore#178]
In vanilla_stall_trace_extension:
```Error: invalid operaiton in operation log: slri```

**Comment by drichmond** [comment]
@bornaehsani I believe this is fixed. Can you mark it as such, if it is

**Comment by bornaehsani** [comment]
Yes it is, it was a typo in the vanilla_core_profiler. Thanks for letting me know!
