### ISSUE TITLE
LLVM installation fails

### ISSUE THREAD

**Issue by tommydcjung** [bespoke-silicon-group/bsg_manycore#188]
/usr/bin/ld: cannot find ../../../../lib/libLLVMSupport.a: No such file or directory
collect2: error: ld returned 1 exit status

@vb000 did you try installing the toolchain from scratch? I think the person modifying the toolchain flow should take ownership of their work, and test that the toolchain build correctly from scratch to ensure seemless out-of-box experience for other developers. It's certainly not the responsibility of others to find out the bug later.

**Comment by dpetrisko** [comment]
Building toolchains is classic fodder for CI, since it intrinsically starts from a clean environment! It’s even cleaner if we build via Docker, since then we can try out different blank slate environments

**Comment by tommydcjung** [comment]
@vb000 seems like you have two choices. Setup CI for building toolchains at least. It seems pretty easy to get started since @dpetrisko did most of the beginning work. Or you can continue to run the testing manually :)

**Comment by vb000** [comment]
> /usr/bin/ld: cannot find ../../../../lib/libLLVMSupport.a: No such file or directory
> collect2: error: ld returned 1 exit status
> 
> @vb000 did you try installing the toolchain from scratch? I think the person modifying the toolchain flow should take ownership of their work, and test that the toolchain build correctly from scratch to ensure seemless out-of-box experience for other developers. It's certainly not the responsibility of others to find out the bug later.

I installed from scratch while running cosim. Not sure what's going wrong...

**Comment by vb000** [comment]
Actually tested it multiple times and tested it again; build is clean. @tommydcjung Could you check if something in your bashrc is causing this?

CI is great -- everyone's on same page to that extent. But since I haven't looked into the process of building a CI flow, I cannot commit to it right now. But I'm happy to talk to Dan about it.
