### ISSUE TITLE
Add bsg_print_stat

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_manycore#189]
At the beginning and end of cuda lite runtime.

**Comment by drichmond** [comment]
On reflection, I'm not sure this is necessary. I think we're fine without it.

**Comment by drichmond** [comment]
People can always add it when they need it - and now with the incoming start/finish macros it'll be pretty straightforward to use.

**Comment by drichmond** [comment]
Closing as Will-Not-Fix / No longer relevant

(Adding Tags to print_stat and kernel_start/end is more powerful)
