### ISSUE TITLE
SIF Async Buffer injects packets into network at reset?

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_manycore#191]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/bcab9c625727016c162567dc8d3bc9ed03767577/v/bsg_manycore_link_sif_async_buffer.v#L9

As per our discussion in the meeting today, @leonardxiang saw this IP injecting packets into the manycore network when the the R reset was asserted, and L reset was not.

Filing this issue for tracking and general awareness

**Comment by leonardxiang** [comment]
To make sure, I recreated the issue by running spmd/test_putchar_stream on bsg_f1 commit ID **d6fece0**.

Yes, as @drichmond said. The R_reset and L_reset are both asserted at the beginning of the simulation.

Two observations:
1. Before the start of manycore traffics, the two resets are **de-asserted** one after another, and no redundant packet is produced.
2. At the end of the simulation, the two reset are **asserted** one after another, and the ansync buffer inject redundant packet.

I would have a closer look at the code here.
https://github.com/bespoke-silicon-group/basejump_stl/blob/6dbdf49e0413c87dfc494fb15c3e295a1bcfb319/bsg_async/bsg_async_ptr_gray.v#L12-L14

**Comment by drichmond** [comment]
We discovered this was an issue with synchronizing resets

**Comment by taylor-bsg** [comment]
what was the solution for the record?

**Comment by drichmond** [comment]
We assert reset on both sides of the clock domain, instead of just one side of the clock domain. The issue occurred in F1 cosimulation at the very end of a simulation so it didn't cause any correctness errors but it did cause simulation errors. 

The last two posts here are a good recap:

https://github.com/bespoke-silicon-group/bsg_f1/pull/434
