### ISSUE TITLE
Parallel recursive cloning not supported in older versions of git

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_manycore#207]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/752bbb852863abc84073bc2341106decab1ae6c9/software/riscv-tools/Makefile#L86

The -j option breaks on older versions of git (namely, the one installed by in Bladerunner on AWS). Can we either remove it, or check the version of git before applying it?

**Comment by vb000** [comment]
I think we can remove it. Would you like me to push a fix?

**Comment by drichmond** [comment]
No... after submitting this I thought about it for a bit. Parallel cloning is nice...

I'd like to update the git version on the Bladerunner machines using IUS if I can. I'm looking into it.

**Comment by vb000** [comment]
Okay!

**Comment by taylor-bsg** [comment]
I think triggering on the version number of git is a good idea. Otherwise,
we need to tell everybody to install a new version of git before using our
stuff?

M

**Comment by vb000** [comment]
Very checking sounds good! I'll add that to the makefile.

**Comment by drichmond** [comment]
I got this fixed on my end (but @taylor-bsg is right, and it seems like @vb000 is on it!)

Good work team!

**Comment by drichmond** [comment]
Was this fixed?

**Comment by vb000** [comment]
Sorry, didn't get a chance to fix this as testing any toolchain mod is quite tedious. I'll try to fix on my issues (:p) right away...

**Comment by vb000** [comment]
Fixed in https://github.com/bespoke-silicon-group/bsg_manycore/pull/225
