### ISSUE TITLE
Missing struct definition causing compilation issue in cosim

### ISSUE THREAD

**Issue by vb000** [bespoke-silicon-group/bsg_manycore#220]
This struct definition seems to be removed in basejump_stl:
https://github.com/bespoke-silicon-group/bsg_manycore/blob/edd5193385731cce755dee3d21f346982a7ab5ad/testbenches/common/v/vcache_profiler.v#L21

The missing definition is causing cosim compilation failure. @tommydcjung Could you have a look? Thanks!

**Comment by tommydcjung** [comment]
should be fixed now.

**Comment by drichmond** [comment]
Which PR fixed it?

**Comment by tommydcjung** [comment]
should have been updated in https://github.com/bespoke-silicon-group/bsg_manycore/pull/209
