### ISSUE TITLE
Split out tile configuration global variables into a separate file

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_manycore#230]
When we compile manycore code for SPMD and CUDA we compile bsg_set_tile_x_y.c, which contains the constants that define the tile x and y. 

It would be nice to separate these, since only SPMD uses the function and loading it into each tile in CUDA is actually a substantial cost.

**Comment by taylor-bsg** [comment]
Presumably this is something that can be fixed with the move to templates
specifying tilegroup dimensions?

M

**Comment by drichmond** [comment]
Yes. It's a bit of an unrelated issue, but yes.

**Comment by taylor-bsg** [comment]
Oh I see what you mean — this is setting each tile X and Y not maxX and maxY

**Comment by drichmond** [comment]
Yes. The method is called in spmd programs, but not in CUDA programs. That is because the CUDA runtime sets the variables.

Despite this, it is still linked and takes up space in the binary. Thus, it can cause significant overhead when loading programs. 

The variables themselves are useful

**Comment by drichmond** [comment]
Addressed in #262
