### ISSUE TITLE
Unexpected Fence behavior

### ISSUE THREAD

**Issue by soctar** [bespoke-silicon-group/bsg_manycore#24]
The `fft_fail_regression` branch has a test that fails (prints number around INT_MAX/INT_MIN) or passes based on a fence instruction. I believe, with non-blocking loads, the fence at `spmd/fft_fail_regress/main.c:34` shouldn't affect the behavior of the program -- this leads me to think that it's a HW issue.

I don't believe it's an issue with multiple cores contending for the same memory location, as the computation operates in phases, where cores have "exclusive" access to memory location until the end of a phase, which is marked by a barrier.

Values listed as {x,y} [even_idx, odd_idx]) where even_idx and odd_idx are indices in a shared array that are being accessed by core {x,y}. Cores read the even index and write both the even and the odd index per phase.

First phase:
{0,1} [2,3]
{0,0} [0,1]
{1,1} [6,7]
{1,0} [4,5]

The second phase:
{0,1} [1,3]
{1,1} [5,7]
{0,0} [0,2]
{1,0} [4,6]

The third phase:
{0,1} [1,5]
{0,0} [0,4]
{1,1} [3,7]
{1,0} [2,6]

I've simplified the code as much as I can while retaining the bug behavior. I'd appreciate some help from HW folks on this.

**Comment by tommydcjung** [comment]
might be nice if it is possible to reproduce the bug with integer access? is the bug related to the pattern of the memory access? might be good to devise a test case where we know what's the expected value, and if we didn't get expected value, the actual value should give some clue about what went wrong.

**Comment by taylor-bsg** [comment]
Hi guys,

Tommy is going to get tracing support back up and running on the manycore
simulator and then we can see if that helps you figure it out, Neil!

M

**Comment by vb000** [comment]
Hi Neil,

Is failing (timeout) either way for me. Any prerequisite for running the
program?

Veluri Bandhav
EE, IIT Roorkee

**Comment by vb000** [comment]
I modified my newlib, so that might be causing this. But strange thing is
that, you're only linking libc.a, libm.a and libgcc.a while I only modified
a library called libgloss.a.

Could you dump the disassembly and give me read access to it?... I'd like
to compare it with mine!

Thanks!

Veluri Bandhav
EE, IIT Roorkee

**Comment by soctar** [comment]
@vb000 I think the timeout's on your end. Disassembly for passing and failing versions below

[fail.txt](https://github.com/bespoke-silicon-group/bsg_manycore/files/3169582/fail.txt)
[pass.txt](https://github.com/bespoke-silicon-group/bsg_manycore/files/3169583/pass.txt)

**Comment by tommydcjung** [comment]
might be a good idea to have a stress test which remote load/store other tiles and validating the results. each store should be a unique value so it is traceable.

**Comment by soctar** [comment]
This has been fixed!! I'll add a regression today.
