### ISSUE TITLE
Bring back the --cycle option for blood graph

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_manycore#281]
Currently, bloodgraph takes in vanilla_stats for timing stats to know what the start and end cycle of the graph should be, but generating bloodgraph should not depend on the stats, but only the traces. So you should bring back the --cycle option as an overriding optional argument.

**Comment by taylor-bsg** [comment]
I think specifying a range is an important option, but maybe also getting
the start and end from the trace file itself would be a useful feature, e.g.

https://github.com/black-parrot/black-parrot/commit/98df9ae4d4990b3a18afeb2c69875642d02aec0a

**Comment by bornaehsani** [comment]
@taylor-bsg  Oh I see, that makes perfects sense! So to my understanding the priority of these options should be in the following order:

1. Default: use the first and last trace from the trace file as start and end cycle
2. If the stats file is given as input, use the first kernel_start and last kernel_end stat --> this narrows the bloodgraph to the window in which the tiles are actually running the kernel
3. If the --cycle option is given, override and use the custom start/end cycle given by the user

Does this make sense? Thanks!

**Comment by taylor-bsg** [comment]
Yep!

**Comment by bornaehsani** [comment]
Addressed in PR #288 . Thanks!
