### ISSUE TITLE
2D array used as a parameter.

### ISSUE THREAD

**Issue by hema0730** [bespoke-silicon-group/bsg_manycore#32]
There's a 2D array of hetero_type_vec_p used as a parameter in bsg_manycore.v. Its dimension is defined by another two parameters of num_tiles_x_p and num_tiles_y_p which have "inv" as their default values. Design Compiler will crash at the very beginning of elaboration without any error messages printed out. It seems like during elaboration, the 2D array parameter will be parsed before the other parameters getting their values from upper levels and using the string of "inv" for specifying the dimension of a 2D array will cause the tool crash. The issue can be resolved by using -1 as the default values for num_tiles_x_p and num_tiles_y_p as we did before. So I believe synthesis tools have more strict rules for using strings as the default values than simulation tools. We may need to be more conservative when we use "inv" for parameters for synthesizability, especially when there's a 2D array in the parameter list.

**Comment by taylor-bsg** [comment]
Sounds okay. Please indicate in a comment that it was changed back from
"inv" and the specific DC version and issue you encountered.

M

**Comment by hema0730** [comment]
@drichmond, Could you give me write access to bsg_manycore repo so that I can push the changes and make a pull request?
