### ISSUE TITLE
y_cord_width_lp and x_cord_width_lp to normal parameter

### ISSUE THREAD

**Issue by stdavids** [bespoke-silicon-group/bsg_manycore#321]
Should this parameter be suffixed _p rather than _lp? If I create a system that extends the manycore left and right then I would want the x_cord_width_lp to be larger than $clog(num_tiles_x_p). I recognize that it is actually a parameter and not a localparam so I am not labeling this a bug; however, for clarity, it seems like we should refactor the name to be just _p with a default value rather than _lp.

https://github.com/bespoke-silicon-group/bsg_manycore/blob/f2bb3b780f598cd81a96f6a9ff0ef3c0e67786f0/v/bsg_manycore.v#L43
https://github.com/bespoke-silicon-group/bsg_manycore/blob/f2bb3b780f598cd81a96f6a9ff0ef3c0e67786f0/v/bsg_manycore.v#L44

**Comment by taylor-bsg** [comment]
_p means changing this is supported; _lp means you better know what you are
doing :-)

**Comment by stdavids** [comment]
Ah okay, then _lp is appropriate.
