### ISSUE TITLE
mulhu Unsupported

### ISSUE THREAD

**Issue by vb000** [bespoke-silicon-group/bsg_manycore#327]
Not sure if this is intentional, manycore says this instruction is not supported:
https://github.com/bespoke-silicon-group/bsg_manycore/blob/5b8e55f846f41d278654a079718ee6c55d495f2b/software/spmd/mulhu_asm_test/main.S#L70-L73

```
"/mnt/users/ssd1/no_backup/bandhav/bsg_bladerunner/bsg_manycore/v/vanilla_bean/vanilla_core.v", 1623: spmd_testbench.DUT.y[1].x[0].tile.proc.h.z.vcore.unnamed$$_4: started at 1256000ps failed at 1256000ps
        Offending '(~id_r.decode.unsupported)'
Error: "/mnt/users/ssd1/no_backup/bandhav/bsg_bladerunner/bsg_manycore/v/vanilla_bean/vanilla_core.v", 1623: spmd_testbench.DUT.y[1].x[0].tile.proc.h.z.vcore.unnamed$$_4: at time 1256000 ps
Unsupported instruction: 0220b0b3
```

Can be reproduced with `mulhu_asm_test` on ` mulhu` branch.

**Comment by taylor-bsg** [comment]
Consider it a success! But maybe we should check for the specific case of
mulhu and print a suitable message?


M

**Comment by taylor-bsg** [comment]
I guess another question is what will it take to tell the compiler not to
use that instruction?

M

**Comment by vb000** [comment]
Yes, I was glad I didn't have to look at trace or worse, the waveform =).

And, I just checked it's intentional!
https://github.com/bespoke-silicon-group/bsg_manycore/blob/25ea084f915e9bce1c2f2119112ab4536034e880/v/vanilla_bean/cl_decode.v#L448-L459

Why don't we support this though?

**Comment by vb000** [comment]
> I guess another question is what will it take to tell the compiler not to use that instruction? 

I'd imagine @tommydcjung would have already looked if there exists a flag. I've an idea how to do this in LLVM, even if there's no flag. Not sure about GCC.

**Comment by dpetrisko** [comment]
> Yes, I was glad I didn't have to look at trace or worse, the waveform =).
> 
> And, I just checked it's intentional!
> 
> https://github.com/bespoke-silicon-group/bsg_manycore/blob/25ea084f915e9bce1c2f2119112ab4536034e880/v/vanilla_bean/cl_decode.v#L448-L459
> 
> Why don't we support this though?

I did some experiments, and the upper 64 bits of a 64 bit multiply cost 60% extra area, for an instruction which is super rare. 

Not sure if there’s a compiler flag, but I do have a subroutine for emulating mulh, if it’s useful. 
https://github.com/black-parrot/black-parrot/blob/master/bp_common/test/src/perch/muldiv.S

**Comment by vb000** [comment]
> I did some experiments, and the upper 64 bits of a 64 bit multiply cost 60% extra area, for an instruction which is super rare. I assume the numbers are similar here.

Cool, thanks!

> Not sure if there’s a compiler flag, but I do have a subroutine for emulating mulh, if it’s useful.
> https://github.com/black-parrot/black-parrot/blob/master/bp_common/test/src/perch/muldiv.S

Those seem to be useful for Manycore too! Could you get the GCC to use those?

**Comment by vb000** [comment]
Closing this as this is deliberate.
