### ISSUE TITLE
NAN >= NAN Inconsistency with both GCC and LLVM

### ISSUE THREAD

**Issue by vb000** [bespoke-silicon-group/bsg_manycore#328]
There seems to be inconsistency with the NAN comparison in the following program:

https://github.com/bespoke-silicon-group/bsg_manycore/blob/e76711485051ed87e3a289bdd8fd126782eaecd8/software/spmd/float_cmp/main.c#L5-L27

Initially I was looking at [`float_all_ops`](https://github.com/bespoke-silicon-group/bsg_replicant/blob/master/examples/cuda/test_float_all_ops.c) failure with LLVM. Then reduced (one of the) failure(s) to this program. Both GCC and LLVM outputs this, because of wrong compile-time resolution in the second case:
```
Error: mismatch with NAN >= NAN:
     Hardcoded comparison reuslted in 0
     Array element comparison reuslted in 1
```

Was worried RISC-V LLVM might be buggy, but am relieved GCC also makes the same mistake =). @bornaehsani @drichmond should we relax `float_all_ops` test considering these compiler inconsistencies?

P.S: the right answer is 0.

**Comment by drichmond** [comment]
Huh. What makes you think that this is an issue in the compiler? Isn't b computed at runtime?

**Comment by vb000** [comment]
From this example, I think, t's illegal to resolve comparison of A[i] >= A[i] as equal because, the standard might say A[i] >= A[i] = 0, when A[i] contains special values like NAN. But it's definitely not desired to prevent compiler from doing these optimizations just to handle NaNs. Not sure what the right solution here is. @sampsyo any thoughts if we should consider this a compiler issue?

**Comment by vb000** [comment]
> Huh. What makes you think that this is an issue in the compiler? Isn't b computed at runtime?

Check in the disassembly that the result is computed at compile time...

**Comment by drichmond** [comment]
OK, so there are no fcmps in the disassembly?

**Comment by vb000** [comment]
Yes, and also we can see `d70` and `d80` instructions, those instructions populate function call arguments (`x11` a.k.a `a1`) for `bsg_printf` call. First one rightly prints `0`, while second one wrongly prints `1`.

**Comment by drichmond** [comment]
Is the assembly similar for both compilers?

**Comment by vb000** [comment]
Yeah, similar:

LLVM:
```
0000012c <main>:
     12c: ff010113            addi  x2,x2,-16
     130: 00112623            sw  x1,12(x2)
     134: 064000ef            jal x1,198 <bsg_set_tile_x_y>
     138: 00001537            lui x10,0x1
     13c: 00c52503            lw  x10,12(x10) # 100c <__bsg_id>
     140: 00050463            beqz  x10,148 <main+0x1c>
     144: 0000006f            j 144 <main+0x18>
     148: 81000537            lui x10,0x81000
     14c: 00050513            mv  x10,x10
     150: 144000ef            jal x1,294 <bsg_printf>
     154: 81000537            lui x10,0x81000
     158: 02250513            addi  x10,x10,34 # 81000022 <_bsg_dram_end_addr+0xfffffeda>
     15c: 00000593            li  x11,0
     160: 134000ef            jal x1,294 <bsg_printf>
     164: 81000537            lui x10,0x81000
     168: 04c50513            addi  x10,x10,76 # 8100004c <_bsg_dram_end_addr+0xffffff04>
     16c: 00100593            li  x11,1
     170: 124000ef            jal x1,294 <bsg_printf>
     174: 00001537            lui x10,0x1
     178: 00852503            lw  x10,8(x10) # 1008 <__bsg_y>
     17c: 000015b7            lui x11,0x1
     180: 0045a583            lw  x11,4(x11) # 1004 <__bsg_x>
     184: 01051513            slli  x10,x10,0x10
     188: 00b50533            add x10,x10,x11
     18c: 4100f5b7            lui x11,0x4100f
     190: aca5ac23            sw  x10,-1320(x11) # 4100ead8 <_bsg_elf_dram_size+0x100ead8>
     194: 0000006f            j 194 <main+0x68>
```

**Comment by taylor-bsg** [comment]
Perhaps this is a flag to tell the compiler to be more strict about NaNs?
Or use no optimization for that function?

**Comment by vb000** [comment]
> Perhaps this is a flag to tell the compiler to be more strict about NaNs? Or use no optimization for that function?

Yes, we'd probably not want to prevent compiler from doing these optimizations. May be there's a pragma to prevent this for each function...

**Comment by taylor-bsg** [comment]
This is just a test though right, not a library function?

**Comment by vb000** [comment]
Yes, just a test. You mean we add a flag for just this test?

**Comment by taylor-bsg** [comment]
yep!

**Comment by vb000** [comment]
After looking into this more, in fact, we explicitly enabled these optimizations here:
https://github.com/bespoke-silicon-group/bsg_manycore/blob/25ea084f915e9bce1c2f2119112ab4536034e880/software/mk/Makefile.builddefs#L85

`-fast-math` enables whole lot of math optimizations including us telling the compiler that there all FP numbers can be assumed to be finite (https://clang.llvm.org/docs/UsersManual.html#id36). The examples, used in the testcase go directly against this. So, we could remove `-ffast-math` just for that testcase.

**Comment by sampsyo** [comment]
Hmm, `-ffast-math` is pretty dangerous—do folks know of particular need to have it enabled globally? It could be prudent to disable it altogether.

In this case, it lets the compiler assume values are not NaN. Obviously that is not true here, so the result is UB. I think @vb000 is right that this UB could explain the wrong code. It is worth at least trying this test without `-ffast-math`.

**Comment by vb000** [comment]
Thanks @sampsyo! Yes, disabling `-ffast-math` fixed this. But added the extra flag, `-fno-fast-math`, on case-by-case basis.

Should we not enable this globally and require kernel author to enable this explicitly?

**Comment by sampsyo** [comment]
Yes! Unless there's a specific, compelling reason not to (and perhaps there is!), I think it would be great idea to disable this flag by default. `-ffast-math` should really be called `-fbroken-fp`. It tells the compiler to violate IEEE 754, so it will make benchmarks/tests that rely on portable semantics (https://github.com/bespoke-silicon-group/bsg_replicant/issues/600?) behave unpredictably.

**Comment by taylor-bsg** [comment]
I think it’s quite likely that we will want some of the optimizations
implied by fast-math in a lot of our ML code, e.g.,

https://forums.sifive.com/t/float-compiler-sqrt/1829

But it does open up a big can of worms. If we have 100 kernels and there is
a 95% chance fast math is okay for each kernel, we have a really good
chance that nothing will work. :-)

It seems like it is a kind of configuration management problem. For each
function we tune, we may want a different set of compilation flags (“user
override”). But we probably want the ability to turn on both “conservative
override” (generate the most correct answers) and “lemming override”
(blindly apply flags so I can tell if these flags could help performance),
and “default mode” — what we think is a reasonable baseline.

I wonder if the python testing stuff Chris is using for PyMTL could be used
to do a flag auto tuner?

M

**Comment by sampsyo** [comment]
Yeah—it might indeed help with ML kernels (as everyone knows, there is no right answer in machine learning). But IMO it would be great to deploy stuff like `-ffast-math` tactically, i.e., when it's likely to be helpful instead of by default.

The fsqrt example is interesting. `-fno-math-errno` might be a more predictable flag for addressing that case specifically. It won't trigger weird stuff like nondeterministic answers for NaNs.

**Comment by save-buffer** [comment]
Another thing we could do is disable `-ffast-math` by default, and then for any function that we find needs it add a `#pragma GCC push_options` and `#pragma GCC pop_options` around the function.

https://gcc.gnu.org/onlinedocs/gcc/Function-Specific-Option-Pragmas.html
