### ISSUE TITLE
LLVM Install Directory

### ISSUE THREAD

**Issue by stdavids** [bespoke-silicon-group/bsg_manycore#38]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/c179c82c3646e9b6d0dee57f0074c592f6345a62/software/spmd/Makefile#L17

We should have a Makefile to build llvm locally inside of the bsg_manycore repo so that we can replicate the llvm build else where. If it is so large that we don't want everyone to have a copy, then we should put the installation outside of a specific user's space and link it inside of bsg_cadenv for that specific machine, but still have the ability to grab a local build for non-bsg users without access to our machines.

**Comment by drichmond** [comment]
Is this related to having a separate repo for manycore tools?

**Comment by stdavids** [comment]
Separate repo or a directory in the current repo (like how risc-v tools is currently built).

**Comment by drichmond** [comment]
At some point we agreed that we'd have a separate repo for tools.

**Comment by stdavids** [comment]
Great, we should include the LLVM build in the tools then and point this to that build directory.

**Comment by drichmond** [comment]
This (may) also solve the issues with everyone cloning and building the RISC-V tools

**Comment by stdavids** [comment]
Agreed. Here is one way it could work: In bsg_manycore we have a makefile target to clone and build the tools (could be a submodule or could just be a git clone + checkout command I'm not too opinionated about that). All tool calls reference this directory. Then, if you are a BSG member on a BSG machine we can have a target to search and symlink this tool repo which will live somewhere common (like where our cad tools are) that is already built and versioned for maintainability.

**Comment by drichmond** [comment]
My thoughts exactly. I would have different versions, too, in case the tools are modified.

**Comment by drichmond** [comment]
Pretty sure I fixed this, but didn't know the issue exists. @stdavids Please reopen if necessary
