### ISSUE TITLE
ffp-contract=fast flag to enable gcc to use fmadd

### ISSUE THREAD

**Issue by marcusnchow** [bespoke-silicon-group/bsg_manycore#393]
ffp-contract is not enabled by default and wanted to put this issue for future reference if people find that gcc is not using fmadd instructions in their own programs

Dustin suggested to might be better off just adding it to manycore so we don't run into this problem again

**Comment by drichmond** [comment]
@taylor-bsg Should we add this as the default? Marcus' toolchain wasn't generating fmadd.

**Comment by taylor-bsg** [comment]
gcc docs say:

The default is -ffp-contract=fast.

Did someone add a flag that turns it off?

I don’t think I have had trouble with it with stock risc-v gcc..

**Comment by drichmond** [comment]
I checked into this today too (see #395  - #397). @marcusnchow I'm not having issues with gcc inserting fmadd. Let's look into this later this week when we meet

**Comment by marcusnchow** [comment]
The issue here is that in the baseline repo is setting it to off in [fragments/kernel/compile.mk](https://github.com/bespoke-silicon-group/baseline/blob/05e5d75e31e968eb7291b7330f00ecb267a4c291/fragments/kernel/compile.mk#L64)

I was basing all of my workloads off of that repo and ran into this issue, but this doesn't affect any other part of hammerblade just baseline

**Comment by drichmond** [comment]
Ahh, then we should fix it there and close this issue. 

(I wonder when I injected that...)
