### ISSUE TITLE
Fix translate_on Spelling Issue

### ISSUE THREAD

**Issue by stdavids** [bespoke-silicon-group/bsg_manycore#41]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/1bc3dbd5b38308480474ca1c634bd9f3310af5da/v/vanilla_bean/vanilla_core.v#L117

Make sure to fix this spelling mistake, causes a whole bunch of synthesis issues :)

**Comment by tommydcjung** [comment]
fixed
