### ISSUE TITLE
AXI interface

### ISSUE THREAD

**Issue by amithmath** [bespoke-silicon-group/bsg_manycore#429]
I was wondering, if one want to integrate BSG Manycore onto SoC, I think one can interface it through AXI?  I was looking at the codes, I think one integrate through this one: https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/v/vanilla_bean/bsg_cache_to_axi_hashed.v ?

**Comment by taylor-bsg** [comment]
Yes — we use this to get to memory in FPGA versions.
