### ISSUE TITLE
should "<" be "<=" instead?

### ISSUE THREAD

**Issue by tommydcjung** [bespoke-silicon-group/bsg_manycore#431]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/software/py/bsg_manycore_link_gen.py#L220

when I try to allocate 4KB space in DMEM (with nothing else), this assertion triggers.

```
.data
  dmem_arr: .space 4096
```

**Comment by tommydcjung** [comment]
```
.data
  dmem_arr: .space 4096
```

**Comment by vb000** [comment]
__dmem_end is 0x1ffc...?

**Comment by tommydcjung** [comment]
Is it? Is "." 0x0 or 0xffffffff at the very beginning?

**Comment by tommydcjung** [comment]
https://sourceware.org/binutils/docs/ld/Location-Counter.html

**Comment by vb000** [comment]
You're right, `__dmem_end` points to the address after the content until that point. It's supposed to be <=.

**Comment by taylor-bsg** [comment]
Appears fixed
