### ISSUE TITLE
Causes an elaboration error

### ISSUE THREAD

**Issue by mrutt92** [bespoke-silicon-group/bsg_manycore#464]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/1c5b2fdf645689c2e2d274996035b3c31608c6e7/v/bsg_manycore_pod_ruche_array.v#L211

```
Error-[IRIPS] Illegal range in part select
bsg_bladerunner/basejump_stl/bsg_tag/bsg_tag_client.v, 94
  The range of the part select is illegal:
  tag_data_r[(width_p - 1):1]
```

**Comment by mrutt92** [comment]
Found this in the ci_bigblade branch.

**Comment by dpetrisko** [comment]
https://github.com/bespoke-silicon-group/basejump_stl/pull/392 

bump basejump?
