### ISSUE TITLE
Macro _bsg_data_end_addr not defined for cosimulation

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_manycore#53]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/824144927aeeb92df461e7bb80652624459d7878/v/vanilla_bean/hobbit.v#L933

When trying to run VCS cosimulation (F1) we don't define _bsg_data_end_addr, so compilation fails. 

Is there a workaround for this? Or do we need to put a macro guard in?

**Comment by vb000** [comment]
This might be because of a failure in previous steps. One of the previous steps extracts _bsg-data_en_addr from the elf. That might have failed.
