### ISSUE TITLE
HW issue: data loss when returned remote load coincides with I$ miss in EXE stage.

### ISSUE THREAD

**Issue by vb000** [bespoke-silicon-group/bsg_manycore#60]
I-cache misses are packaged as remote load requests to DRAM. Since, i-caches misses cannot be non-blocking, they are stalled in MEM stage until the core gets a response. When a non-blocking remote load response arrives when i-cache miss remote load is in EXE stage, this [line]( https://github.com/bespoke-silicon-group/bsg_manycore/blob/0bd9aa12f10445935af7a50f78844c7f1ee180a8/v/vanilla_bean/hobbit.v#L892) will cause the data loss.

A clean solution is to not insert remote loads with icache-miss remote loads. This will not cause any loss in performance as icache-misses would anyway stall in MEM stage. And, arriving remote loads can be committed directly to reg file during these stall cycles.

**Comment by taylor-bsg** [comment]
Nice! Was this found with newlib/dramfs?

M

**Comment by vb000** [comment]
Yes! But this corner was hit only when we stack is in DRAM.

**Comment by tommydcjung** [comment]
I think the changes in  fpu branch handles this corner case correctly.

**Comment by vb000** [comment]
@tommydcjung Yes, I too think fpu branch handles this particular case, but I've a question about a different but related scenario: I see you allow inserting remote load response with an i-cache miss! But i-cache miss stalls in mem stage until data arrives, right? So, what about the data you get from the icache-miss response? Won't it overwrite the remote load response you inserted along with i-cache miss?

**Comment by tommydcjung** [comment]
no it doesn't overwrite the inserted data. ifetch_instr_i writes straight into icache, while icache bubble is waiting in MEM stage.

https://github.com/bespoke-silicon-group/bsg_manycore/pull/62/files#diff-a1dc929e9bb25544cc677422a57a4e7aR736

**Comment by vb000** [comment]
sounds good!
