### ISSUE TITLE
icache vs DMEM memory access

### ISSUE THREAD

**Issue by natewise** [bespoke-silicon-group/bsg_manycore#663]
Hello, so I have a question regarding instruction cache vs scratchpad/DMEM memory access.

I have a program that I plan to run across 2 tiles, that uses ~8.3KB of memory in lookup tables and local data structures. I want to run the program on only one tile (say tile 0), and use the other tile (say tile 1) as a sort of memory bank, where I'd like to utilize both tile 1's 4KB of icache and 4KB of scratchpad/DMEM for memory storage. 
So say I have 3 lookup tables like so:
`uint32_t LUT1[256] = {...}; uint32_t LUT2[256] = {...}; uint32_t LUT3[256] = {...};`

How could I ensure LUT1 is stored in DMEM of tile 0, LUT2 on icache of tile 1 and LUT3 on DMEM of tile 1?

**Comment by dpetrisko** [comment]
Hi, for something like this you will probably want to use CUDA lite host calls. In the SPMD loader included in this repo, the same exact program is run on each tile allocated. Thus there is no way to statically differentiate between tiles.

Allocations can be made statically in DMEM by annotating the correct linker section (.dmem I believe). I'm not sure if the I$ can be statically allocated as scratchpad. In either case, you'll need to fill the data from the host core or "main.c" in the cuda code. This will allow you to copy to the correct lookup tables to each individual memory. There may be helper functions to copy or may not be, but the coordinates/addresses can always be calculated based on the technical reference manual tables

**Comment by taylor-bsg** [comment]
@tommydcjung can you take a stab at a reply and offer any pointers to example code? My guess is the answer is things should be stored in DRAM first and then each tile, based on its ID will load the data it needs. Although this is something that has been considered, the I-cache is not currently usable as a scratchpad.
