### ISSUE TITLE
Use SSH for cloning BSG Repos, not HTTPS

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_manycore#68]
Using https in private repositories forces users to enter input when building the RISC-V tools: https://github.com/bespoke-silicon-group/bsg_manycore/blob/996fef087c3da33c697a206826eb010ec755cee1/software/riscv-tools/Makefile#L32

**Comment by max-ruttenberg** [comment]
@vb000 yeah... this is super brutal

**Comment by max-ruttenberg** [comment]
This bug forces us to babysit our terminals while the riscv-tool chain clone because it requires our username and password at some point in the process. This really needs to be fixed ASAP.
