### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by Yuan-Mao** [bespoke-silicon-group/bsg_manycore#696]
The following lines might need some attention:

1. https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/v/bsg_manycore_pod_mesh_array.v#L106
Although it might actually be compatible, but global_x_li (and also global_y_li) has different dimension than the one declared in bsg_manycore_pod_mesh_row.v:
https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/v/bsg_manycore_pod_mesh_row.v#L83

2. https://github.com/bespoke-silicon-group/bsg_manycore/blob/master/v/bsg_manycore_tile_compute_array_mesh.v#L117
Should use subarray_num_tiles_[xy]_p instead of num_tiles_[xy]_p.

**Comment by taylor-bsg** [comment]
@tommydcjung is this resolved

**Comment by tommydcjung** [comment]
1 is not a bug.
2 is fixed here: https://github.com/bespoke-silicon-group/bsg_manycore/pull/728
