### ISSUE TITLE
bsg_manycore synthesis  in DC 

### ISSUE THREAD

**Issue by amithmath** [bespoke-silicon-group/bsg_manycore#727]
I was going through this makefile: https://github.com/tommydcjung/bsg_manycore/blob/master/syn/Makefile.dc can any one please tell me what/where is $(BERKELEY_TARGET)? I did grep, find, in bsg_bladerunner directory,  I couldn't locate any.

**Comment by taylor-bsg** [comment]
Appears to be a stale fork?

**Comment by amithmath** [comment]
Yes it's old repo and currently, I am using this repo.
