### ISSUE TITLE
HW: MAX comparison between sNAN and valid float fails

### ISSUE THREAD

**Issue by vb000** [bespoke-silicon-group/bsg_manycore#78]
For the values `a_i = 0x7f800001` and `b_i=0x3f800000`, `max_o=0x3f800000`. But hw outputs `max_o=0x7fc00000 (qNAN)`. Revisit the priority mux [here](https://github.com/bespoke-silicon-group/basejump_stl/blob/e8b50e70d9b8d3eaa29dc70150ff2f05b534d750/bsg_fpu/bsg_fpu_cmp.v#L156).

To reproduce the issue: `make fmin.riscv_tests_run` in `software/spmd/bsg_riscv_tests`

**Comment by taylor-bsg** [comment]
So:

a. 3f8... is 1.0

b. 0x7f8000001 is signaling NaN

c. 0x3f8* is 1.0 (the simulator output)

d. 7fc... is quiet NaN?  (which our HW outputs)

RISC-V spec:

https://github.com/riscv/riscv-isa-manual/releases/download/draft-20190625-cc95103/riscv-spec.pdf

Floating-point minimum-number and maximum-number instructions FMIN.S and FMAX.S write, respectively, the smaller or larger of rs1 and rs2 to rd. For the purposes of these instructions only, the value −0.0 is considered to be less than the value +0.0. If both inputs are NaNs, the result is the canonical NaN. **If only one operand is a NaN, the result is the non-NaN operand.** Signaling NaN inputs set the invalid operation exception  ag, even when the result is not NaN.

**Comment by taylor-bsg** [comment]
@tommydcjung Seems like a straightforward bug?

**Comment by vb000** [comment]
All riscv isa test passing on tapeout_hb_rc0.3!
