### ISSUE TITLE
These functions are deprecated, use bsg_printf instead 

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_manycore#85]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/e7139dec9e73810d7dc4a13b6c8542fda8289e60/software/spmd/bsg_cuda_lite_runtime/packet/kernel_packet.c#L22

**Comment by drichmond** [comment]
Fixed?

**Comment by bornaehsani** [comment]
Yes, addressed in PR #100.
