### ISSUE TITLE
Separate bsg_barrier into a srouce and header file 

### ISSUE THREAD

**Issue by bornaehsani** [bespoke-silicon-group/bsg_manycore#86]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/e7139dec9e73810d7dc4a13b6c8542fda8289e60/software/bsg_manycore_lib/bsg_barrier.h#L1

If we want to use barrier in both cuda kernels and the cuda lite runtime software this is needed.

**Comment by drichmond** [comment]
Fixed?

**Comment by bornaehsani** [comment]
Not yet, on my to do list.

**Comment by bornaehsani** [comment]
Deprecated, replaced by the templatized C++ bsg_tile_group_barrier.hpp.
