### ISSUE TITLE
Fast CUDA memset/memcpy

### ISSUE THREAD

**Issue by mrutt92** [bespoke-silicon-group/bsg_manycore#98]
Currently the bandwidth between the host and the manycore would be a bottleneck for doing simple ops like memcpy and memset. These ops are primitives that could be needed in more complex applications. Already in GraphIt we've found use for setting an entire vector in manycore memory to a single value. 

It would be cool if there was a kernel, maybe one that was always present in the CUDA runtime (so the host could rely on it being there) that could do a parallel memcpy/memset. We sorta already have the kernel `vec_set` (which is like memset) which doesn't seem to be optimized (but it would be trivial). 

Not urgent, but I thought I'd make a note to see what people thought.

**Comment by taylor-bsg** [comment]
Understanding the source of the bottlenecks would also be useful, after the
Aug 1 deadline.  I know there are a couple of RTL issues in the Xilinx code
that are making us be very conservative about putting things across the
PCIe bus. After that, then there is optimizing the software to allow lots
of concurrent LD/ST (maybe with hardware offload of credit counting). At
the extremes, then it is about optimizing PCIe bus traffic and maybe having
multiple host ports on the machine.

M

**Comment by drichmond** [comment]
Addressed in #182
